# Connexion MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/treasurySight_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=nazha

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

mindee.api.key=md_6CsxkH_WwEUNTkeDUzU7wcIXwDu96IFm2oqFuMKOe_A